### ISSUE TITLE
Add the ability to highlight subscriber messages with a specific color

### ISSUE THREAD

**Issue by MSPAIN3** [Chatterino/chatterino2#2000]
**What should be added?**
When you're mentioned or someone subs, that message has a color that really stands out, since i'm always showing my chat on stream i would love to be able to highlight all of the messages my subscribers send with a specific color that i could choose.

**Why should it be added?**
It would be really helpful and i think most people would like to have the option to do this

**Comment by fourtf** [comment]
Would be covered by https://github.com/Chatterino/chatterino2/issues/1696

**Comment by leon-richardt** [comment]
> Would be covered by #1696

Actually, PR #1704 does not implement badge-based highlights for subscribers according to the PR description. (And #1696 does not explicitly ask for it either.)

**Comment by leon-richardt** [comment]
The desired behavior can almost be achieved by #1748. You can set up a filter to only show messages by subscribers in a specific split.

**Comment by zneix** [comment]
@MSPAIN3 this should be covered with Channel filters introduced in #1748, See https://wiki.chatterino.com/Filters. If you feel like that doesn't cover your needs (or have any other questions) feel free to comment on the issue, @mention me and I can reopen the issue if necessary.
